@startuml
title Important Domain Classes
class User
class VerifyCode
class Chat
class Message
class PersonalInfo
class CV
class Feedback
User "1" -- "*" Chat
Chat "1" -- "*" Message
User "1" -- "0..1" PersonalInfo
User "1" -- "*" CV
User "1" -- "*" Feedback
User "1" -- "*" VerifyCode
@enduml
