-- Seed normalized skill catalog data.

INSERT INTO skill (name, category, category_id)
VALUES
('Java', 'Programming Languages', 1),
('Python', 'Programming Languages', 1),
('JavaScript', 'Programming Languages', 1),
('TypeScript', 'Programming Languages', 1),
('C', 'Programming Languages', 1),
('C++', 'Programming Languages', 1),
('C#', 'Programming Languages', 1),
('Go', 'Programming Languages', 1),
('Rust', 'Programming Languages', 1),
('PHP', 'Programming Languages', 1),
('Ruby', 'Programming Languages', 1),
('Swift', 'Programming Languages', 1),
('Kotlin', 'Programming Languages', 1),
('Dart', 'Programming Languages', 1),
('Scala', 'Programming Languages', 1),
('R', 'Programming Languages', 1),
('MATLAB', 'Programming Languages', 1),
('Bash', 'Programming Languages', 1),
('PowerShell', 'Programming Languages', 1),
('SQL', 'Programming Languages', 1),
('HTML', 'Programming Languages', 1),
('CSS', 'Programming Languages', 1),
('Sass', 'Programming Languages', 1),
('Less', 'Programming Languages', 1),
('Lua', 'Programming Languages', 1),
('Perl', 'Programming Languages', 1),
('Objective-C', 'Programming Languages', 1),
('Groovy', 'Programming Languages', 1),
('Visual Basic', 'Programming Languages', 1),
('Assembly', 'Programming Languages', 1),
('Haskell', 'Programming Languages', 1),
('Elixir', 'Programming Languages', 1),
('Erlang', 'Programming Languages', 1),
('React', 'Frontend Development', 2),
('Angular', 'Frontend Development', 2),
('Vue.js', 'Frontend Development', 2),
('Svelte', 'Frontend Development', 2),
('Next.js', 'Frontend Development', 2),
('Nuxt.js', 'Frontend Development', 2),
('Remix', 'Frontend Development', 2),
('Vite', 'Frontend Development', 2),
('Webpack', 'Frontend Development', 2),
('Babel', 'Frontend Development', 2),
('Tailwind CSS', 'Frontend Development', 2),
('Bootstrap', 'Frontend Development', 2),
('Material UI', 'Frontend Development', 2),
('Chakra UI', 'Frontend Development', 2),
('Redux', 'Frontend Development', 2),
('Zustand', 'Frontend Development', 2),
('React Query', 'Frontend Development', 2),
('Axios', 'Frontend Development', 2),
('jQuery', 'Frontend Development', 2),
('Responsive Design', 'Frontend Development', 2),
('Web Accessibility', 'Frontend Development', 2),
('Progressive Web Apps', 'Frontend Development', 2),
('Single Page Applications', 'Frontend Development', 2),
('Server-Side Rendering', 'Frontend Development', 2),
('Frontend Performance', 'Frontend Development', 2),
('DOM Manipulation', 'Frontend Development', 2),
('CSS Grid', 'Frontend Development', 2),
('Flexbox', 'Frontend Development', 2),
('Spring Boot', 'Backend Development', 3),
('Spring Framework', 'Backend Development', 3),
('Node.js', 'Backend Development', 3),
('Express.js', 'Backend Development', 3),
('NestJS', 'Backend Development', 3),
('Django', 'Backend Development', 3),
('Flask', 'Backend Development', 3),
('FastAPI', 'Backend Development', 3),
('Laravel', 'Backend Development', 3),
('Symfony', 'Backend Development', 3),
('ASP.NET Core', 'Backend Development', 3),
('Ruby on Rails', 'Backend Development', 3),
('REST APIs', 'Backend Development', 3),
('GraphQL', 'Backend Development', 3),
('gRPC', 'Backend Development', 3),
('Microservices', 'Backend Development', 3),
('Monolithic Architecture', 'Backend Development', 3),
('API Design', 'Backend Development', 3),
('Authentication', 'Backend Development', 3),
('Authorization', 'Backend Development', 3),
('JWT', 'Backend Development', 3),
('OAuth2', 'Backend Development', 3),
('OpenAPI', 'Backend Development', 3),
('Swagger', 'Backend Development', 3),
('Hibernate', 'Backend Development', 3),
('JPA', 'Backend Development', 3),
('Entity Framework', 'Backend Development', 3),
('Message Queues', 'Backend Development', 3),
('RabbitMQ', 'Backend Development', 3),
('Kafka', 'Backend Development', 3),
('Redis Caching', 'Backend Development', 3),
('Background Jobs', 'Backend Development', 3),
('WebSockets', 'Backend Development', 3),
('Server-Sent Events', 'Backend Development', 3),
('Android Development', 'Mobile Development', 4),
('iOS Development', 'Mobile Development', 4),
('React Native', 'Mobile Development', 4),
('Flutter', 'Mobile Development', 4),
('SwiftUI', 'Mobile Development', 4),
('UIKit', 'Mobile Development', 4),
('Jetpack Compose', 'Mobile Development', 4),
('Android SDK', 'Mobile Development', 4),
('iOS SDK', 'Mobile Development', 4),
('Mobile UI Design', 'Mobile Development', 4),
('Mobile App Testing', 'Mobile Development', 4),
('Firebase', 'Mobile Development', 4),
('Push Notifications', 'Mobile Development', 4),
('In-App Purchases', 'Mobile Development', 4),
('App Store Deployment', 'Mobile Development', 4),
('Google Play Deployment', 'Mobile Development', 4),
('Mobile Performance', 'Mobile Development', 4),
('Offline-First Apps', 'Mobile Development', 4),
('Mobile Security', 'Mobile Development', 4),
('Expo', 'Mobile Development', 4),
('Ionic', 'Mobile Development', 4),
('Cordova', 'Mobile Development', 4),
('Kotlin Multiplatform', 'Mobile Development', 4),
('Native Modules', 'Mobile Development', 4),
('PostgreSQL', 'Database', 5),
('MySQL', 'Database', 5),
('MariaDB', 'Database', 5),
('SQLite', 'Database', 5),
('Oracle Database', 'Database', 5),
('Microsoft SQL Server', 'Database', 5),
('MongoDB', 'Database', 5),
('DynamoDB', 'Database', 5),
('Cassandra', 'Database', 5),
('Elasticsearch', 'Database', 5),
('Neo4j', 'Database', 5),
('Firebase Firestore', 'Database', 5),
('Database Design', 'Database', 5),
('Data Modeling', 'Database', 5),
('Normalization', 'Database', 5),
('Indexing', 'Database', 5),
('Query Optimization', 'Database', 5),
('Stored Procedures', 'Database', 5),
('Database Migration', 'Database', 5),
('Flyway', 'Database', 5),
('Liquibase', 'Database', 5),
('Transactions', 'Database', 5),
('ACID', 'Database', 5),
('NoSQL Databases', 'Database', 5),
('Data Warehousing', 'Database', 5),
('ETL', 'Database', 5),
('OLAP', 'Database', 5),
('Backup and Recovery', 'Database', 5),
('Database Replication', 'Database', 5),
('Docker', 'DevOps & Cloud', 6),
('Docker Compose', 'DevOps & Cloud', 6),
('Kubernetes', 'DevOps & Cloud', 6),
('Helm', 'DevOps & Cloud', 6),
('Terraform', 'DevOps & Cloud', 6),
('Ansible', 'DevOps & Cloud', 6),
('Jenkins', 'DevOps & Cloud', 6),
('GitHub Actions', 'DevOps & Cloud', 6),
('GitLab CI', 'DevOps & Cloud', 6),
('CircleCI', 'DevOps & Cloud', 6),
('AWS', 'DevOps & Cloud', 6),
('Azure', 'DevOps & Cloud', 6),
('Google Cloud Platform', 'DevOps & Cloud', 6),
('Linux Administration', 'DevOps & Cloud', 6),
('Nginx', 'DevOps & Cloud', 6),
('Apache HTTP Server', 'DevOps & Cloud', 6),
('Load Balancing', 'DevOps & Cloud', 6),
('CI/CD', 'DevOps & Cloud', 6),
('Infrastructure as Code', 'DevOps & Cloud', 6),
('Monitoring', 'DevOps & Cloud', 6),
('Prometheus', 'DevOps & Cloud', 6),
('Grafana', 'DevOps & Cloud', 6),
('ELK Stack', 'DevOps & Cloud', 6),
('CloudFormation', 'DevOps & Cloud', 6),
('Serverless', 'DevOps & Cloud', 6),
('AWS Lambda', 'DevOps & Cloud', 6),
('Azure Functions', 'DevOps & Cloud', 6),
('Cloud Run', 'DevOps & Cloud', 6),
('Networking Basics', 'DevOps & Cloud', 6),
('DNS', 'DevOps & Cloud', 6),
('SSL/TLS', 'DevOps & Cloud', 6),
('Reverse Proxy', 'DevOps & Cloud', 6),
('Container Orchestration', 'DevOps & Cloud', 6),
('Excel', 'Data & Analytics', 7),
('Advanced Excel', 'Data & Analytics', 7),
('Google Sheets', 'Data & Analytics', 7),
('Data Analysis', 'Data & Analytics', 7),
('Data Visualization', 'Data & Analytics', 7),
('Power BI', 'Data & Analytics', 7),
('Tableau', 'Data & Analytics', 7),
('Looker Studio', 'Data & Analytics', 7),
('Pandas', 'Data & Analytics', 7),
('NumPy', 'Data & Analytics', 7),
('SciPy', 'Data & Analytics', 7),
('Jupyter Notebook', 'Data & Analytics', 7),
('Matplotlib', 'Data & Analytics', 7),
('Plotly', 'Data & Analytics', 7),
('Statistics', 'Data & Analytics', 7),
('Probability', 'Data & Analytics', 7),
('Regression Analysis', 'Data & Analytics', 7),
('A/B Testing', 'Data & Analytics', 7),
('Business Intelligence', 'Data & Analytics', 7),
('Data Cleaning', 'Data & Analytics', 7),
('Data Wrangling', 'Data & Analytics', 7),
('Data Mining', 'Data & Analytics', 7),
('Dashboard Design', 'Data & Analytics', 7),
('KPI Reporting', 'Data & Analytics', 7),
('SQL Analytics', 'Data & Analytics', 7),
('BigQuery', 'Data & Analytics', 7),
('Snowflake', 'Data & Analytics', 7),
('Apache Spark', 'Data & Analytics', 7),
('PySpark', 'Data & Analytics', 7),
('Airflow', 'Data & Analytics', 7),
('Data Pipelines', 'Data & Analytics', 7),
('Data Governance', 'Data & Analytics', 7),
('Machine Learning', 'AI & Machine Learning', 8),
('Deep Learning', 'AI & Machine Learning', 8),
('Natural Language Processing', 'AI & Machine Learning', 8),
('Computer Vision', 'AI & Machine Learning', 8),
('Generative AI', 'AI & Machine Learning', 8),
('Large Language Models', 'AI & Machine Learning', 8),
('Prompt Engineering', 'AI & Machine Learning', 8),
('RAG', 'AI & Machine Learning', 8),
('Vector Databases', 'AI & Machine Learning', 8),
('Embeddings', 'AI & Machine Learning', 8),
('TensorFlow', 'AI & Machine Learning', 8),
('PyTorch', 'AI & Machine Learning', 8),
('Keras', 'AI & Machine Learning', 8),
('Scikit-learn', 'AI & Machine Learning', 8),
('Hugging Face', 'AI & Machine Learning', 8),
('OpenAI API', 'AI & Machine Learning', 8),
('LangChain', 'AI & Machine Learning', 8),
('LlamaIndex', 'AI & Machine Learning', 8),
('Model Evaluation', 'AI & Machine Learning', 8),
('Feature Engineering', 'AI & Machine Learning', 8),
('Model Deployment', 'AI & Machine Learning', 8),
('MLOps', 'AI & Machine Learning', 8),
('Fine-Tuning', 'AI & Machine Learning', 8),
('Classification', 'AI & Machine Learning', 8),
('Clustering', 'AI & Machine Learning', 8),
('Recommendation Systems', 'AI & Machine Learning', 8),
('Time Series Forecasting', 'AI & Machine Learning', 8),
('Neural Networks', 'AI & Machine Learning', 8),
('Transformers', 'AI & Machine Learning', 8),
('Image Processing', 'AI & Machine Learning', 8),
('Cybersecurity Fundamentals', 'Cybersecurity', 9),
('Network Security', 'Cybersecurity', 9),
('Application Security', 'Cybersecurity', 9),
('Web Security', 'Cybersecurity', 9),
('OWASP Top 10', 'Cybersecurity', 9),
('Penetration Testing', 'Cybersecurity', 9),
('Vulnerability Assessment', 'Cybersecurity', 9),
('Threat Modeling', 'Cybersecurity', 9),
('Security Auditing', 'Cybersecurity', 9),
('Encryption', 'Cybersecurity', 9),
('Cryptography', 'Cybersecurity', 9),
('Identity and Access Management', 'Cybersecurity', 9),
('SIEM', 'Cybersecurity', 9),
('Incident Response', 'Cybersecurity', 9),
('Digital Forensics', 'Cybersecurity', 9),
('Malware Analysis', 'Cybersecurity', 9),
('Cloud Security', 'Cybersecurity', 9),
('Container Security', 'Cybersecurity', 9),
('Secure Coding', 'Cybersecurity', 9),
('Security Testing', 'Cybersecurity', 9),
('Firewall Management', 'Cybersecurity', 9),
('Endpoint Security', 'Cybersecurity', 9),
('Risk Assessment', 'Cybersecurity', 9),
('Compliance', 'Cybersecurity', 9),
('ISO 27001', 'Cybersecurity', 9),
('SOC 2', 'Cybersecurity', 9),
('Data Privacy', 'Cybersecurity', 9),
('Manual Testing', 'Testing & QA', 10),
('Automated Testing', 'Testing & QA', 10),
('Unit Testing', 'Testing & QA', 10),
('Integration Testing', 'Testing & QA', 10),
('End-to-End Testing', 'Testing & QA', 10),
('Regression Testing', 'Testing & QA', 10),
('Performance Testing', 'Testing & QA', 10),
('Load Testing', 'Testing & QA', 10),
('API Testing', 'Testing & QA', 10),
('Mobile Testing', 'Testing & QA', 10),
('Test Planning', 'Testing & QA', 10),
('Test Case Design', 'Testing & QA', 10),
('Bug Reporting', 'Testing & QA', 10),
('Selenium', 'Testing & QA', 10),
('Cypress', 'Testing & QA', 10),
('Playwright', 'Testing & QA', 10),
('JUnit', 'Testing & QA', 10),
('Mockito', 'Testing & QA', 10),
('Jest', 'Testing & QA', 10),
('Vitest', 'Testing & QA', 10),
('React Testing Library', 'Testing & QA', 10),
('Postman', 'Testing & QA', 10),
('Newman', 'Testing & QA', 10),
('JMeter', 'Testing & QA', 10),
('Cucumber', 'Testing & QA', 10),
('BDD', 'Testing & QA', 10),
('TDD', 'Testing & QA', 10),
('Quality Assurance', 'Testing & QA', 10),
('UI Design', 'UI/UX & Design', 11),
('UX Design', 'UI/UX & Design', 11),
('User Research', 'UI/UX & Design', 11),
('Wireframing', 'UI/UX & Design', 11),
('Prototyping', 'UI/UX & Design', 11),
('Figma', 'UI/UX & Design', 11),
('Adobe XD', 'UI/UX & Design', 11),
('Sketch', 'UI/UX & Design', 11),
('Design Systems', 'UI/UX & Design', 11),
('Interaction Design', 'UI/UX & Design', 11),
('Information Architecture', 'UI/UX & Design', 11),
('Usability Testing', 'UI/UX & Design', 11),
('User Journey Mapping', 'UI/UX & Design', 11),
('Persona Creation', 'UI/UX & Design', 11),
('Visual Design', 'UI/UX & Design', 11),
('Typography', 'UI/UX & Design', 11),
('Color Theory', 'UI/UX & Design', 11),
('Icon Design', 'UI/UX & Design', 11),
('Branding', 'UI/UX & Design', 11),
('Accessibility Design', 'UI/UX & Design', 11),
('Mobile Design', 'UI/UX & Design', 11),
('Web Design', 'UI/UX & Design', 11),
('Landing Page Design', 'UI/UX & Design', 11),
('Design Thinking', 'UI/UX & Design', 11),
('Framer', 'UI/UX & Design', 11),
('Product Management', 'Product & Project Management', 12),
('Project Management', 'Product & Project Management', 12),
('Agile Methodology', 'Product & Project Management', 12),
('Scrum', 'Product & Project Management', 12),
('Kanban', 'Product & Project Management', 12),
('Jira', 'Product & Project Management', 12),
('Trello', 'Product & Project Management', 12),
('Asana', 'Product & Project Management', 12),
('Notion', 'Product & Project Management', 12),
('Roadmap Planning', 'Product & Project Management', 12),
('Backlog Management', 'Product & Project Management', 12),
('Sprint Planning', 'Product & Project Management', 12),
('User Stories', 'Product & Project Management', 12),
('Requirements Gathering', 'Product & Project Management', 12),
('Stakeholder Management', 'Product & Project Management', 12),
('Risk Management', 'Product & Project Management', 12),
('Resource Planning', 'Product & Project Management', 12),
('Timeline Estimation', 'Product & Project Management', 12),
('Product Strategy', 'Product & Project Management', 12),
('Market Research', 'Product & Project Management', 12),
('Competitor Analysis', 'Product & Project Management', 12),
('MVP Planning', 'Product & Project Management', 12),
('OKRs', 'Product & Project Management', 12),
('KPIs', 'Product & Project Management', 12),
('Product Analytics', 'Product & Project Management', 12),
('Change Management', 'Product & Project Management', 12),
('Documentation', 'Product & Project Management', 12),
('Digital Marketing', 'Business & Marketing', 13),
('Content Marketing', 'Business & Marketing', 13),
('SEO', 'Business & Marketing', 13),
('SEM', 'Business & Marketing', 13),
('Google Ads', 'Business & Marketing', 13),
('Meta Ads', 'Business & Marketing', 13),
('Email Marketing', 'Business & Marketing', 13),
('Social Media Marketing', 'Business & Marketing', 13),
('Copywriting', 'Business & Marketing', 13),
('Content Writing', 'Business & Marketing', 13),
('Brand Strategy', 'Business & Marketing', 13),
('Sales', 'Business & Marketing', 13),
('Customer Relationship Management', 'Business & Marketing', 13),
('HubSpot', 'Business & Marketing', 13),
('Salesforce', 'Business & Marketing', 13),
('Lead Generation', 'Business & Marketing', 13),
('Growth Marketing', 'Business & Marketing', 13),
('Marketing Analytics', 'Business & Marketing', 13),
('Google Analytics', 'Business & Marketing', 13),
('Conversion Rate Optimization', 'Business & Marketing', 13),
('Public Relations', 'Business & Marketing', 13),
('Community Management', 'Business & Marketing', 13),
('E-commerce', 'Business & Marketing', 13),
('Shopify', 'Business & Marketing', 13),
('Customer Support', 'Business & Marketing', 13),
('Negotiation', 'Business & Marketing', 13),
('Accounting', 'Finance & Accounting', 14),
('Financial Accounting', 'Finance & Accounting', 14),
('Managerial Accounting', 'Finance & Accounting', 14),
('Bookkeeping', 'Finance & Accounting', 14),
('Financial Analysis', 'Finance & Accounting', 14),
('Financial Modeling', 'Finance & Accounting', 14),
('Budgeting', 'Finance & Accounting', 14),
('Forecasting', 'Finance & Accounting', 14),
('Cost Accounting', 'Finance & Accounting', 14),
('Auditing', 'Finance & Accounting', 14),
('Tax Preparation', 'Finance & Accounting', 14),
('Payroll', 'Finance & Accounting', 14),
('Accounts Payable', 'Finance & Accounting', 14),
('Accounts Receivable', 'Finance & Accounting', 14),
('QuickBooks', 'Finance & Accounting', 14),
('SAP Finance', 'Finance & Accounting', 14),
('Excel Financial Modeling', 'Finance & Accounting', 14),
('Investment Analysis', 'Finance & Accounting', 14),
('Risk Analysis', 'Finance & Accounting', 14),
('Corporate Finance', 'Finance & Accounting', 14),
('Banking Operations', 'Finance & Accounting', 14),
('Financial Reporting', 'Finance & Accounting', 14),
('IFRS', 'Finance & Accounting', 14),
('GAAP', 'Finance & Accounting', 14),
('Cash Flow Analysis', 'Finance & Accounting', 14),
('Communication', 'Communication & Soft Skills', 15),
('Teamwork', 'Communication & Soft Skills', 15),
('Problem Solving', 'Communication & Soft Skills', 15),
('Critical Thinking', 'Communication & Soft Skills', 15),
('Leadership', 'Communication & Soft Skills', 15),
('Time Management', 'Communication & Soft Skills', 15),
('Adaptability', 'Communication & Soft Skills', 15),
('Creativity', 'Communication & Soft Skills', 15),
('Attention to Detail', 'Communication & Soft Skills', 15),
('Presentation Skills', 'Communication & Soft Skills', 15),
('Public Speaking', 'Communication & Soft Skills', 15),
('Conflict Resolution', 'Communication & Soft Skills', 15),
('Decision Making', 'Communication & Soft Skills', 15),
('Emotional Intelligence', 'Communication & Soft Skills', 15),
('Active Listening', 'Communication & Soft Skills', 15),
('Collaboration', 'Communication & Soft Skills', 15),
('Customer Service', 'Communication & Soft Skills', 15),
('Mentoring', 'Communication & Soft Skills', 15),
('Analytical Thinking', 'Communication & Soft Skills', 15),
('Self-Motivation', 'Communication & Soft Skills', 15),
('Organization', 'Communication & Soft Skills', 15),
('Professional Writing', 'Communication & Soft Skills', 15),
('Research Skills', 'Communication & Soft Skills', 15),
('Learning Agility', 'Communication & Soft Skills', 15),
('Work Ethic', 'Communication & Soft Skills', 15),
('Microsoft Word', 'Office & Productivity Tools', 16),
('Microsoft Excel', 'Office & Productivity Tools', 16),
('Microsoft PowerPoint', 'Office & Productivity Tools', 16),
('Microsoft Outlook', 'Office & Productivity Tools', 16),
('Google Docs', 'Office & Productivity Tools', 16),
('Google Slides', 'Office & Productivity Tools', 16),
('Google Drive', 'Office & Productivity Tools', 16),
('Microsoft Teams', 'Office & Productivity Tools', 16),
('Slack', 'Office & Productivity Tools', 16),
('Zoom', 'Office & Productivity Tools', 16),
('Notion Workspace', 'Office & Productivity Tools', 16),
('Airtable', 'Office & Productivity Tools', 16),
('Trello Boards', 'Office & Productivity Tools', 16),
('Canva Presentations', 'Office & Productivity Tools', 16),
('Document Formatting', 'Office & Productivity Tools', 16),
('Email Management', 'Office & Productivity Tools', 16),
('Calendar Management', 'Office & Productivity Tools', 16),
('Data Entry', 'Office & Productivity Tools', 16),
('File Organization', 'Office & Productivity Tools', 16),
('PDF Editing', 'Office & Productivity Tools', 16),
('Report Writing', 'Office & Productivity Tools', 16),
('Presentation Design', 'Office & Productivity Tools', 16),
('AutoCAD', 'Engineering & CAD', 17),
('SolidWorks', 'Engineering & CAD', 17),
('CATIA', 'Engineering & CAD', 17),
('Fusion 360', 'Engineering & CAD', 17),
('Revit', 'Engineering & CAD', 17),
('SketchUp', 'Engineering & CAD', 17),
('MATLAB Simulink', 'Engineering & CAD', 17),
('Arduino', 'Engineering & CAD', 17),
('Raspberry Pi', 'Engineering & CAD', 17),
('PCB Design', 'Engineering & CAD', 17),
('Circuit Design', 'Engineering & CAD', 17),
('Electrical Engineering', 'Engineering & CAD', 17),
('Mechanical Design', 'Engineering & CAD', 17),
('Civil Engineering', 'Engineering & CAD', 17),
('Structural Analysis', 'Engineering & CAD', 17),
('3D Modeling', 'Engineering & CAD', 17),
('3D Printing', 'Engineering & CAD', 17),
('Robotics', 'Engineering & CAD', 17),
('PLC Programming', 'Engineering & CAD', 17),
('Instrumentation', 'Engineering & CAD', 17),
('Control Systems', 'Engineering & CAD', 17),
('CAD Drafting', 'Engineering & CAD', 17),
('BIM', 'Engineering & CAD', 17),
('Finite Element Analysis', 'Engineering & CAD', 17),
('Thermodynamics', 'Engineering & CAD', 17),
('Fluid Mechanics', 'Engineering & CAD', 17),
('Manufacturing Processes', 'Engineering & CAD', 17),
('Biology', 'Healthcare & Science', 18),
('Chemistry', 'Healthcare & Science', 18),
('Physics', 'Healthcare & Science', 18),
('Laboratory Techniques', 'Healthcare & Science', 18),
('Clinical Research', 'Healthcare & Science', 18),
('Medical Terminology', 'Healthcare & Science', 18),
('Anatomy', 'Healthcare & Science', 18),
('Physiology', 'Healthcare & Science', 18),
('Microbiology', 'Healthcare & Science', 18),
('Biochemistry', 'Healthcare & Science', 18),
('Genetics', 'Healthcare & Science', 18),
('Pharmacology', 'Healthcare & Science', 18),
('Public Health', 'Healthcare & Science', 18),
('Epidemiology', 'Healthcare & Science', 18),
('Healthcare Administration', 'Healthcare & Science', 18),
('Patient Care', 'Healthcare & Science', 18),
('First Aid', 'Healthcare & Science', 18),
('CPR', 'Healthcare & Science', 18),
('Nursing Fundamentals', 'Healthcare & Science', 18),
('Scientific Writing', 'Healthcare & Science', 18),
('Research Methodology', 'Healthcare & Science', 18),
('SPSS', 'Healthcare & Science', 18),
('Bioinformatics', 'Healthcare & Science', 18),
('Quality Control', 'Healthcare & Science', 18),
('Lab Safety', 'Healthcare & Science', 18)
ON CONFLICT (name) DO UPDATE
SET category = EXCLUDED.category,
    category_id = EXCLUDED.category_id,
    updated_at = NOW();
