package com.uniai.chat.application.planning;

/** Explicit, read-only routes that the graduate AI planner may select. */
public enum GraduateAiRoute {
    DIRECT_AI_RESPONSE,
    GET_GRADUATE_OVERVIEW,

    LIST_UNIVERSITIES,
    SEARCH_UNIVERSITIES,
    GET_UNIVERSITY_DETAILS,
    COUNT_UNIVERSITIES,
    LIST_UNIVERSITIES_BY_CITY,
    COMPARE_UNIVERSITIES,

    LIST_CAMPUSES,
    SEARCH_CAMPUSES,
    GET_CAMPUS_DETAILS,
    CHECK_CAMPUS_EXISTS,
    COUNT_CAMPUSES,
    COMPARE_CAMPUS_COUNTS,

    LIST_FACULTIES,
    SEARCH_FACULTIES,
    GET_FACULTY_DETAILS,
    COUNT_FACULTIES,
    LIST_DEPARTMENTS,
    SEARCH_DEPARTMENTS,
    GET_DEPARTMENT_DETAILS,
    COUNT_DEPARTMENTS,

    LIST_PROGRAMS,
    SEARCH_PROGRAMS,
    CHECK_PROGRAM_EXISTS,
    GET_PROGRAM_DETAILS,
    LIST_PROGRAM_TRACKS,
    LIST_PROGRAM_LANGUAGES,
    LIST_PROGRAM_SOURCES,
    COUNT_PROGRAMS,
    COUNT_PROGRAMS_BY_UNIVERSITY,
    COUNT_PROGRAMS_BY_FACULTY,
    COUNT_PROGRAMS_BY_DEPARTMENT,
    COMPARE_PROGRAM_AVAILABILITY,
    COMPARE_PROGRAM_COUNTS,

    GET_TUITION,
    GET_PROGRAM_TUITION,
    GET_FACULTY_TUITION,
    GET_DEPARTMENT_TUITION,
    GET_UNIVERSITY_TUITION,
    GET_MINIMUM_TUITION,
    GET_MAXIMUM_TUITION,
    GET_AVERAGE_TUITION,
    COMPARE_TUITION,
    LIST_FEE_ITEMS,

    GET_ADMISSION_REQUIREMENTS,
    GET_LANGUAGE_REQUIREMENTS,
    GET_TEST_REQUIREMENTS,
    LIST_REQUIRED_DOCUMENTS,
    GET_APPLICATION_DEADLINES,
    CHECK_ADMISSION_REQUIREMENT,
    COMPARE_ADMISSION_REQUIREMENTS,

    LIST_SCHOLARSHIPS,
    LIST_FINANCIAL_AID,
    LIST_PAYMENT_PLANS,
    LIST_ACCREDITATIONS
}
