package com.uniai.chat.domain.builder;

import com.uniai.chat.domain.model.Chat;
import com.uniai.chat.domain.model.Message;

import java.time.LocalDateTime;

/**
 * Domain builder for {@link Message}.
 *
 * <p>Two named factory methods make the intent self-documenting at every call
 * site — eliminating the magic {@code senderId = 0L} literal that previously
 * leaked into the application layer.
 *
 * <p>Timestamp is always set to {@link LocalDateTime#now()} at build time,
 * consistent with the {@code @PrePersist} guard on the entity itself.
 */
public final class MessageBuilder {

    /** Sentinel value that identifies every AI-generated message. */
    public static final long AI_SENDER_ID = 0L;

    private Chat   chat;
    private Long   senderId;
    private String content;

    private MessageBuilder() {}

    // -------------------------------------------------------------------------
    // Named factory methods
    // -------------------------------------------------------------------------

    /** Builds a message authored by a human user. */
    public static MessageBuilder userMessage(Chat chat, Long userId, String content) {
        MessageBuilder b = new MessageBuilder();
        b.chat     = chat;
        b.senderId = userId;
        b.content  = content;
        return b;
    }

    /**
     * Builds a message generated by the AI service.
     * Sets {@code senderId} to {@value AI_SENDER_ID}.
     */
    public static MessageBuilder aiMessage(Chat chat, String content) {
        MessageBuilder b = new MessageBuilder();
        b.chat     = chat;
        b.senderId = AI_SENDER_ID;
        b.content  = content;
        return b;
    }

    // -------------------------------------------------------------------------
    // Terminal
    // -------------------------------------------------------------------------

    public Message build() {
        return Message.builder()
                .chat(chat)
                .senderId(senderId)
                .content(content)
                .timestamp(LocalDateTime.now())
                .build();
    }
}
